import { Category, Product } from '../models/store.models';

export interface DemoThemeConfig {
  id: string;
  name: string;
  segment: string;
  badge: string;
  tagline: string;
  description: string;
  aboutEyebrow: string;
  aboutTitle: string;
  aboutText: string;
  heroImage: string;
  logoUrl: string;
  fullLogoUrl: string;
  whatsappNumber: string;
  whatsappFormatted: string;
  email: string;
  businessHours: string;
  primaryColor: string;
  primaryContrast: string;
  secondaryColor: string;
  backgroundColor: string;
  sectionBg?: string;
  headerBg: string;
  headerBorder: string;
  perks: { title: string; desc: string }[];
  categories: Category[];
  products: Product[];
}

export const DEMO_THEMES: Record<string, DemoThemeConfig> = {
  // =========================================================================
  // 1. LUME — FUTUREWEAR & TECH APPAREL (TEMA OFICIAL)
  // =========================================================================
  lume: {
    id: 'lume',
    name: 'Lume',
    segment: 'Futurewear & Tech Apparel',
    badge: 'MARCA OFICIAL // WHITE-LABEL',
    tagline: 'FUTUREWEAR & TECH APPAREL',
    description: 'Peças desenvolvidas com design futurista, tecidos tecnológicos de alta respirabilidade e caimento impecável. A marca oficial que une tecnologia, alta conversão e moda.',
    aboutEyebrow: 'LUME OFICIAL',
    aboutTitle: 'Tecnologia de ponta em cada costura.',
    aboutText: 'A Lume combina estética cyber-minimalista, tecidos tecnológicos respiráveis com proteção UV50+ e modelagens anatômicas contemporâneas. Estilo inteligente para quem dita o futuro.',
    heroImage: '/images/hero-lume.jpg',
    logoUrl: '/images/lume-icon.png',
    fullLogoUrl: '/images/lume-logo.png',
    whatsappNumber: '5511999998888',
    whatsappFormatted: '+55 11 99999-8888',
    email: 'contato@lume.com.br',
    businessHours: 'Segunda a Sábado — 09:00 às 20:00',
    primaryColor: '#0DF5A4',
    primaryContrast: '#000000',
    secondaryColor: '#FFFFFF',
    backgroundColor: '#080809',
    sectionBg: '#080809',
    headerBg: 'rgba(8, 8, 9, 0.95)',
    headerBorder: 'rgba(13, 245, 164, 0.25)',
    perks: [
      { title: 'TECNOLOGIA CYBER DRY & REFLECT', desc: 'Fibras inteligentes respiráveis com detalhes refletivos e proteção UV50+' },
      { title: 'MODELAGENS ANATÔMICAS TECH', desc: 'Caimento ergonômico projetado para mobilidade e presença visual marcante' }
    ],
    categories: [
      {
        id: 'cat-lum-1',
        name: 'Camisetas Tech & Cyber',
        slug: 'camisetas-tech',
        description: 'Camisetas em malha tecnológica de alta gramatura com toque sedoso e detalhes neon.',
        image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80'
      },
      {
        id: 'cat-lum-2',
        name: 'Hoodies & Agasalhos Futuristas',
        slug: 'hoodies-agasalhos',
        description: 'Moletons tecnológicos estruturados e agasalhos com acabamento futurista.',
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80'
      },
      {
        id: 'cat-lum-3',
        name: 'Calças Táticas & Cargo Tech',
        slug: 'calcas-taticas',
        description: 'Calças utilitárias com múltiplos bolsos e ajuste ergonômico nos tornozelos.',
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80'
      },
      {
        id: 'cat-lum-4',
        name: 'Jaquetas Corta-Vento & Modular',
        slug: 'jaquetas-corta-ventos',
        description: 'Corta-ventos repelentes à água e casacos térmicos de alta performance.',
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'
      }
    ],
    products: [
      {
        id: 'lum-1',
        sku: 'LUM-CAM-001',
        name: 'Camiseta Cyber Tech Neon Glow',
        slug: 'camiseta-cyber-tech-neon-glow',
        description: 'Camiseta masculina e unissex confeccionada em malha tecnológica dry-cotton com acabamento sedoso e detalhe minimalista glow neon. Máxima respirabilidade e estilo contemporâneo.',
        price: 159.90,
        promotionalPrice: 139.90,
        images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&q=85', 'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=1000&q=85'],
        categoryId: 'cat-lum-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Verde Neon Glow', hex: '#0df5a4' }, { name: 'Deep Cyber Black', hex: '#080809' }, { name: 'Branco Puro', hex: '#ffffff' }],
        composition: '92% Poliamida Tecnológica Dry, 8% Elastano Nobre',
        fit: 'Modern Athletic Fit',
        washCare: 'Lavagem suave à máquina (até 30°C). Não passar a ferro quente.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'lum-2',
        sku: 'LUM-HOD-002',
        name: 'Hoodie Futurewear Reflective 420g',
        slug: 'hoodie-futurewear-reflective-420g',
        description: 'Moletom 3 cabos 420g com forro peluciado macio, capuz duplo estruturado e estampa minimalista com pigmento refletivo no escuro. O equilíbrio ideal entre conforto térmico e vanguarda.',
        price: 319.90,
        promotionalPrice: 289.90,
        images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1000&q=85', 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=1000&q=85'],
        categoryId: 'cat-lum-2',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Deep Cyber Black', hex: '#080809' }, { name: 'Neon Accent', hex: '#0df5a4' }],
        composition: '80% Algodão Premium, 20% Fibras Térmicas Respiráveis',
        fit: 'Boxy Oversized Fit',
        washCare: 'Lavar do avesso em água fria. Secar à sombra.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'lum-3',
        sku: 'LUM-CAR-003',
        name: 'Calça Jogger Tática Ripstop Lume',
        slug: 'calca-jogger-tatica-ripstop-lume',
        description: 'Calça utilitária em tecido ripstop militar com acabamento repelente a respingos e rasgos. 6 bolsos ergonômicos, cintura com cordão embutido e ajuste nos tornozelos.',
        price: 269.90,
        images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=1000&q=85'],
        categoryId: 'cat-lum-3',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'All Black Tático', hex: '#080809' }, { name: 'Cinza Titânio', hex: '#27272a' }],
        composition: '100% Algodão Ripstop Estruturado',
        fit: 'Ergonomic Tapered Fit',
        washCare: 'Lavagem em máquina até 40°C.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'lum-4',
        sku: 'LUM-JKT-004',
        name: 'Corta-Vento Cyber Shield Impermeável',
        slug: 'corta-vento-cyber-shield-impermeavel',
        description: 'Jaqueta corta-vento ultraleve corta-frio com membrana impermeável e zíper selado emborrachado. Pesa apenas 220g e acompanha bolsinho integrado para transporte compacto.',
        price: 249.90,
        promotionalPrice: 219.90,
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=1000&q=85'],
        categoryId: 'cat-lum-4',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Deep Cyber Black', hex: '#080809' }, { name: 'Verde Neon Details', hex: '#0df5a4' }],
        composition: '100% Nylon Ultralight Shield Ripstop',
        fit: 'Athletic Slim Fit',
        washCare: 'Não passar a ferro. Lavagem rápida com sabão neutro.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'lum-5',
        sku: 'LUM-REG-005',
        name: 'Regata Techwear Laser Microperfurada',
        slug: 'regata-techwear-laser-microperfurada',
        description: 'Regata de caimento moderno com microperfurações a laser na região dorsal para ventilação térmica dinâmica. Tecido antibacteriano com fios de prata.',
        price: 129.90,
        images: ['https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=1000&q=85'],
        categoryId: 'cat-lum-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Deep Cyber Black', hex: '#080809' }, { name: 'Verde Neon', hex: '#0df5a4' }],
        composition: '90% Poliamida Tecnológica Dry, 10% Elastano',
        fit: 'Athletic Fitted',
        washCare: 'Lavagem rápida à máquina. Secagem instantânea ao ar.',
        available: true,
        featured: false,
        isNew: true
      },
      {
        id: 'lum-6',
        sku: 'LUM-PAR-006',
        name: 'Calça Parachute Cyber Tactical Cordão',
        slug: 'calca-parachute-cyber-tactical-cordao',
        description: 'Calça parachute em nylon taslan com toque peletizado, cós largo com elástico reforçado e stoppers metálicos nos tornozelos para modelagem versátil.',
        price: 279.90,
        promotionalPrice: 249.90,
        images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=1000&q=85'],
        categoryId: 'cat-lum-3',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'Deep Cyber Black', hex: '#080809' }, { name: 'Cinza Concreto', hex: '#4b5563' }],
        composition: '100% Nylon Taslan Hidrorrepelente',
        fit: 'Parachute Relaxed Fit',
        washCare: 'Lavar à mão ou em ciclo delicado.',
        available: true,
        featured: false,
        isNew: true
      },
      {
        id: 'lum-7',
        sku: 'LUM-MOD-007',
        name: 'Jaqueta Modular Bomber Arneses Removíveis',
        slug: 'jaqueta-modular-bomber-arneses-removiveis',
        description: 'Jaqueta bomber de estética futurista com fitas táticas funcionais e bolso manga com zíper selado. Forro acetinado térmico de alta respirabilidade.',
        price: 389.90,
        promotionalPrice: 349.90,
        images: ['https://images.unsplash.com/photo-1520975954732-35dd22299614?w=1000&q=85'],
        categoryId: 'cat-lum-4',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Deep Cyber Black', hex: '#080809' }],
        composition: '100% Poliéster Estruturado com Membrana Corta-Vento',
        fit: 'Modern Bomber Fit',
        washCare: 'Limpeza a seco ou lavagem manual suave.',
        available: true,
        featured: true,
        isNew: false
      }
    ]
  },

  // =========================================================================
  // 2. OLIVEIRA — FITNESS & CASUAL (MODA ESPORTIVA)
  // =========================================================================
  oliveira: {
    id: 'oliveira',
    name: 'Oliveira',
    segment: 'Fitness & Casual',
    badge: 'MODA ESPORTIVA',
    tagline: 'MODA ESPORTIVA E CASUAL',
    description: 'Moda esportiva e casual masculina e feminina. Peças com máxima elasticidade, respirabilidade e caimento impecável para treinos intensos e uso diário.',
    aboutEyebrow: 'A MARCA',
    aboutTitle: 'Performance no treino. Estilo nos passeios.',
    aboutText: 'A Oliveira cria peças esportivas e casuais masculinas e femininas com tecidos inteligentes, respirabilidade e caimento impecável. Do treino pesado na academia aos momentos casuais de lazer, viva o seu melhor estilo com máxima atitude.',
    heroImage: '/images/hero-couple-fitness.jpg',
    logoUrl: '/images/oliveira-icon.png',
    fullLogoUrl: '/images/oliveira-logo.png',
    whatsappNumber: '5511963041542',
    whatsappFormatted: '+55 11 96304-1542',
    email: 'contato@oliveiramoda.com.br',
    businessHours: 'Segunda a Sábado — 09:00 às 19:00',
    primaryColor: '#CCA45E',
    primaryContrast: '#0A152E',
    secondaryColor: '#CBD5E1',
    backgroundColor: '#0A152E',
    sectionBg: '#0A152E',
    headerBg: 'rgba(10, 21, 46, 0.98)',
    headerBorder: 'rgba(204, 164, 94, 0.2)',
    perks: [
      { title: 'TECNOLOGIA DRY & FLEX', desc: 'Tecidos respiráveis de alta elasticidade e conforto térmico' },
      { title: 'ACADEMIA & PASSEIOS', desc: 'Modelagens versáteis do treino pesado ao dia a dia' }
    ],
    categories: [
      {
        id: 'cat-fit-1',
        name: 'Camisetas & Tops Performance',
        slug: 'camisetas-tops',
        description: 'Camisetas dry-fit, regatas e tops para treino intenso e uso casual.',
        image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80'
      },
      {
        id: 'cat-fit-2',
        name: 'Calças & Leggings Modeladoras',
        slug: 'calcas-leggings',
        description: 'Leggings modeladoras de alta compressão e calças joggers esportivas.',
        image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80'
      },
      {
        id: 'cat-fit-3',
        name: 'Bermudas & Shorts Esportivos',
        slug: 'bermudas-shorts',
        description: 'Bermudas 2 em 1 de compressão e shorts leves para treino e lazer.',
        image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&q=80'
      },
      {
        id: 'cat-fit-4',
        name: 'Casacos & Corta-Ventos Running',
        slug: 'casacos-jaquetas',
        description: 'Windbreakers, jaquetas esportivas e agasalhos para treino e passeios.',
        image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80'
      }
    ],
    products: [
      {
        id: 'oli-1',
        sku: 'OLI-CAM-001',
        name: 'Camiseta Dry-Fit Tech Performance',
        slug: 'camiseta-dry-fit-tech-performance',
        description: 'Camiseta masculina de alta performance em microfibra dry com elastano. Respirabilidade máxima, secagem ultrarrápida e proteção UV50+.',
        price: 139.90,
        promotionalPrice: 119.90,
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=1000&q=85'],
        categoryId: 'cat-fit-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Azul Marinho', hex: '#0a152e' }, { name: 'Branco Puro', hex: '#ffffff' }, { name: 'Dourado Nobre', hex: '#cca45e' }],
        composition: '90% Poliamida Dry, 10% Elastano',
        fit: 'Slim Athletic Fit',
        washCare: 'Lavagem suave à máquina (até 30°C). Não secar em secadora.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'oli-2',
        sku: 'OLI-TOP-002',
        name: 'Top Fitness Cross Back Sustentação',
        slug: 'top-fitness-cross-back-sustentacao',
        description: 'Top fitness feminino com alças cruzadas nas costas para distribuição anatômica de peso. Média compressão e bojo removível.',
        price: 119.90,
        promotionalPrice: 99.90,
        images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1000&q=85', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1000&q=85'],
        categoryId: 'cat-fit-1',
        sizes: ['P', 'M', 'G'],
        colors: [{ name: 'Azul Marinho', hex: '#0a152e' }, { name: 'Off-White', hex: '#f8fafc' }],
        composition: '84% Poliamida, 16% Spandex com Proteção UV',
        fit: 'Alta Sustentação Anatômica',
        washCare: 'Lavar à mão ou em saquinho protetor.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'oli-3',
        sku: 'OLI-LEG-003',
        name: 'Legging Esculp Safe Cintura Alta',
        slug: 'legging-esculp-safe-cintura-alta',
        description: 'Legging com compressão estratégica que modela sem apertar. Tecido encorpado zero transparência com bolso invisível para celular.',
        price: 189.90,
        images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=1000&q=85', 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=1000&q=85'],
        categoryId: 'cat-fit-2',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Preto Intenso', hex: '#0a0a0a' }, { name: 'Azul Marinho', hex: '#0a152e' }],
        composition: '78% Poliamida, 22% Elastano Power',
        fit: 'Compressão Modeladora',
        washCare: 'Lavagem delicada em água fria.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'oli-4',
        sku: 'OLI-BER-004',
        name: 'Bermuda 2 em 1 Force com Compressão Interna',
        slug: 'bermuda-2-em-1-force-compressao',
        description: 'Bermuda masculina com forro interno de compressão anti-atrito e bolso celular. Camada externa leve e respirável.',
        price: 149.90,
        images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=1000&q=85', 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1000&q=85'],
        categoryId: 'cat-fit-3',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Preto Grafite', hex: '#18181b' }, { name: 'Azul Marinho Real', hex: '#0a152e' }],
        composition: '92% Poliéster reciclado, 8% Elastano',
        fit: 'Regular com Bermuda Interna Compression',
        washCare: 'Lavar à máquina em ciclo rápido.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'oli-5',
        sku: 'OLI-WND-005',
        name: 'Corta-Vento Running Ultralight Refletivo',
        slug: 'corta-vento-running-ultralight-refletivo',
        description: 'Jaqueta corta-vento em microfibra ultraleve com acabamento repelente a água, abertura para ventilação nas costas e faixas refletivas 360° para treinos noturnos.',
        price: 239.90,
        promotionalPrice: 209.90,
        images: ['https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=1000&q=85'],
        categoryId: 'cat-fit-4',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Azul Marinho', hex: '#0a152e' }, { name: 'Dourado Nobre', hex: '#cca45e' }],
        composition: '100% Poliamida Ultralight Ripstop',
        fit: 'Athletic Streamlined',
        washCare: 'Lavagem rápida com sabão neutro.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'oli-6',
        sku: 'OLI-REG-006',
        name: 'Regata Masculina Muscle Fit Treino',
        slug: 'regata-masculina-muscle-fit-treino',
        description: 'Regata cavada com caimento atlético muscle fit em poliamida dry com toque gelado. Costuras flatlock anti-atrito para máxima liberdade nos treinos de força.',
        price: 109.90,
        images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=1000&q=85'],
        categoryId: 'cat-fit-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Chumbo Escuro', hex: '#27272a' }, { name: 'Branco Óptico', hex: '#ffffff' }],
        composition: '91% Poliamida Dry Touch, 9% Spandex',
        fit: 'Muscle Athletic Fit',
        washCare: 'Lavagem em máquina até 30°C.',
        available: true,
        featured: false,
        isNew: false
      },
      {
        id: 'oli-7',
        sku: 'OLI-JOG-007',
        name: 'Calça Jogger Sport Training Flex 4-Way',
        slug: 'calca-jogger-sport-training-flex-4-way',
        description: 'Calça jogger unissex em moletinho tecnológico com elastano 4-way stretch. Cós elástico largo anatômico, bolsos com zíper selado e punho ergonômico.',
        price: 219.90,
        images: ['https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=1000&q=85', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1000&q=85'],
        categoryId: 'cat-fit-2',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Azul Marinho Real', hex: '#0a152e' }, { name: 'Preto Ônix', hex: '#09090b' }],
        composition: '68% Algodão Nobre, 26% Poliéster, 6% Elastano',
        fit: 'Athletic Jogger Fit',
        washCare: 'Lavagem à máquina em ciclo suave.',
        available: true,
        featured: false,
        isNew: true
      }
    ]
  },

  // =========================================================================
  // 3. BARONE IMPORTS — STREETWEAR & URBAN CULTURE
  // =========================================================================
  barone: {
    id: 'barone',
    name: 'Barone Imports',
    segment: 'Streetwear & Urban Culture',
    badge: 'CULTURA URBANA',
    tagline: 'HEAVYWEIGHT STREETWEAR',
    description: 'Moda de rua autêntica, modelagens oversized e tecidos heavyweight 260g/m² desenvolvidos para o homem contemporâneo. Estilo que dita as regras nas ruas.',
    aboutEyebrow: 'MANIFESTO STREET',
    aboutTitle: 'Do asfalto para o mundo. Atitude heavyweight.',
    aboutText: 'A Barone Imports traduz a cultura urbana com tecidos encorpados de alta gramatura, caimento boxy oversized e estética minimalista de impacto visual.',
    heroImage: '/images/hero-streetwear.jpg',
    logoUrl: '/images/barone-logo.png',
    fullLogoUrl: '/images/barone-logo.png',
    whatsappNumber: '5511999990001',
    whatsappFormatted: '+55 11 99999-0001',
    email: 'drops@baronestore.com.br',
    businessHours: 'Segunda a Sábado — 10:00 às 20:00',
    primaryColor: '#FFFFFF',
    primaryContrast: '#000000',
    secondaryColor: '#E63946',
    backgroundColor: '#080809',
    sectionBg: '#080809',
    headerBg: 'rgba(8, 8, 9, 0.98)',
    headerBorder: 'rgba(255, 255, 255, 0.15)',
    perks: [
      { title: 'HEAVYWEIGHT COTTON 260G', desc: 'Tecidos encorpados com caimento estruturado e lavagem acid' },
      { title: 'DROPS & EDIÇÃO LIMITADA', desc: 'Lotes numerados e modelagens exclusivas boxy fit' }
    ],
    categories: [
      {
        id: 'cat-st-1',
        name: 'Camisetas Heavyweight & Boxy',
        slug: 'camisetas-oversized',
        description: 'Tees de alta gramatura com caimento boxy e gola canelada 3cm.',
        image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80'
      },
      {
        id: 'cat-st-2',
        name: 'Hoodies & Moletons 420g',
        slug: 'hoodies-agasalhos',
        description: 'Moletons 3 cabos pesados flanelados com capuz duplo estruturado.',
        image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=600&q=80'
      },
      {
        id: 'cat-st-3',
        name: 'Calças Cargo & Skate Pants',
        slug: 'calcas-cargo',
        description: 'Calças utilitárias com bolsos fole e ajuste anatômico nos tornozelos.',
        image: 'https://images.unsplash.com/photo-1516826957135-700dedea698c?w=600&q=80'
      },
      {
        id: 'cat-st-4',
        name: 'Jaquetas Varsity & Workwear',
        slug: 'jaquetas-varsity',
        description: 'Jaquetas college de feltro, sarja encorpada e casacos streetwear.',
        image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&q=80'
      }
    ],
    products: [
      {
        id: 'bar-1',
        sku: 'BAR-TEE-001',
        name: 'Camiseta Boxy Heavyweight 260g Black',
        slug: 'camiseta-boxy-heavyweight-260g-black',
        description: 'Camiseta oversized confeccionada em malha premium 100% algodão penteado 260g. Gola canelada 3cm anti-esgarçamento e caimento boxy imponente.',
        price: 159.90,
        promotionalPrice: 139.90,
        images: ['https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?w=1000&q=85'],
        categoryId: 'cat-st-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Preto Intenso', hex: '#080809' }, { name: 'Off-White Acid', hex: '#e4e4e7' }],
        composition: '100% Algodão Penteado Heavyweight 260g',
        fit: 'Boxy Oversized Fit',
        washCare: 'Lavar do avesso em água fria. Não passar sobre as estampas.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'bar-2',
        sku: 'BAR-HOD-002',
        name: 'Hoodie Acid Wash Heavyweight 420g',
        slug: 'hoodie-acid-wash-heavyweight-420g',
        description: 'Moletom 3 cabos 420g com lavagem estonada acid wash exclusiva. Capuz estruturado sem cordão e bolso canguru embutido.',
        price: 289.90,
        images: ['https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=1000&q=85'],
        categoryId: 'cat-st-2',
        sizes: ['M', 'G', 'GG'],
        colors: [{ name: 'Cinza Grafite Acid', hex: '#27272a' }, { name: 'Preto Vintage', hex: '#18181b' }],
        composition: '80% Algodão, 20% Poliéster Encorpado',
        fit: 'Drop Shoulder Relaxed',
        washCare: 'Lavagem suave com sabão neutro. Secar na horizontal.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'bar-3',
        sku: 'BAR-CAR-003',
        name: 'Calça Cargo Utilitária Tática Ripstop',
        slug: 'calca-cargo-utilitaria-tatica-ripstop',
        description: 'Calça cargo em sarja ripstop militar com 6 bolsos amplos com fole, cordão de ajuste no tornozelo e reforço de costura dupla nos joelhos.',
        price: 249.90,
        images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1000&q=85', 'https://images.unsplash.com/photo-1516826957135-700dedea698c?w=1000&q=85'],
        categoryId: 'cat-st-3',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'All Black', hex: '#080809' }, { name: 'Verde Oliva Militar', hex: '#3f4238' }],
        composition: '100% Algodão Ripstop Militar',
        fit: 'Loose Tapered Leg',
        washCare: 'Lavar à máquina até 40°C.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'bar-4',
        sku: 'BAR-TEE-004',
        name: 'Camiseta Oversized Graphic Drop Tokyo',
        slug: 'camiseta-oversized-graphic-drop-tokyo',
        description: 'Camiseta oversized 260g em puro algodão com estampa serigráfica em relevo nas costas com tema metrópole contemporânea. Costura reforçada ombro a ombro.',
        price: 169.90,
        promotionalPrice: 149.90,
        images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1000&q=85', 'https://images.unsplash.com/photo-1527719327859-c6ce80353573?w=1000&q=85'],
        categoryId: 'cat-st-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Off-White Craquelado', hex: '#f4f4f5' }, { name: 'Preto Carbono', hex: '#09090b' }],
        composition: '100% Algodão Heavyweight 260g',
        fit: 'Drop Shoulder Boxy',
        washCare: 'Lavar do avesso com água fria.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'bar-5',
        sku: 'BAR-VAR-005',
        name: 'Jaqueta Varsity College Streetwear Barone',
        slug: 'jaqueta-varsity-college-streetwear-barone',
        description: 'Jaqueta college clássica streetwear com mangas contrastantes, corpo em feltro encorpado, patches bordados em chenille e botões de pressão metálicos esmaltados.',
        price: 369.90,
        promotionalPrice: 329.90,
        images: ['https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=1000&q=85'],
        categoryId: 'cat-st-4',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Preto & Branco', hex: '#09090b' }, { name: 'Verde Vintage & Creme', hex: '#1b3b22' }],
        composition: 'Corpo: 70% Lã Sintética Feltro, Mangas: 100% Poliuretano Macio',
        fit: 'Classic Varsity Boxy',
        washCare: 'Limpeza a seco especializada.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'bar-6',
        sku: 'BAR-JNS-006',
        name: 'Calça Denim Skate Loose Fit 14oz',
        slug: 'calca-denim-skate-loose-fit-14oz',
        description: 'Jeans 100% algodão 14oz com lavagem clara estonada vintage, perna ampla loose fit skate e costuras pespontadas duplas para resistir à lixa e ao asfalto.',
        price: 269.90,
        images: ['https://images.unsplash.com/photo-1516826957135-700dedea698c?w=1000&q=85'],
        categoryId: 'cat-st-3',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'Azul Claro Vintage', hex: '#64748b' }, { name: 'Preto Envelhecido', hex: '#27272a' }],
        composition: '100% Algodão Denim 14oz',
        fit: 'Wide Leg Loose Skate',
        washCare: 'Lavar à máquina do avesso em água fria.',
        available: true,
        featured: false,
        isNew: false
      },
      {
        id: 'bar-7',
        sku: 'BAR-BER-007',
        name: 'Bermuda Sweatpants Heavy Oversized 380g',
        slug: 'bermuda-sweatpants-heavy-oversized-380g',
        description: 'Bermuda de moletom felpado 380g com corte desestruturado acima do joelho, bolsos laterais fundos e cordão grosso de algodão cru com ponteiras de metal.',
        price: 179.90,
        images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1000&q=85', 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=1000&q=85'],
        categoryId: 'cat-st-3',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Cinza Mescla Ash', hex: '#d4d4d8' }, { name: 'Preto Intenso', hex: '#09090b' }],
        composition: '100% Algodão Moletom 380g',
        fit: 'Relaxed Drop Fit',
        washCare: 'Lavar do avesso com sabão neutro.',
        available: true,
        featured: false,
        isNew: true
      }
    ]
  },

  // =========================================================================
  // 4. MARÉ — RESORT & BEACHWEAR (ALTO VERÃO & LINHO PURO)
  // =========================================================================
  mare: {
    id: 'mare',
    name: 'Maré',
    segment: 'Resort & Beachwear',
    badge: 'ALTO VERÃO',
    tagline: 'RESORT & CASUAL LINEN',
    description: 'Fibras naturais de puro linho europeu, alfaiataria leve e modelagens fluidas pensadas para os dias de sol, momentos de lazer e o pós-praia com sofisticação.',
    aboutEyebrow: 'ALTO VERÃO',
    aboutTitle: 'A brisa do litoral em cada detalhe.',
    aboutText: 'A Maré nasce da união entre o frescor das praias e o requinte da alfaiataria leve. Roupas respiráveis em linho e algodão nobre para quem vive o verão o ano inteiro.',
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=85',
    logoUrl: '/images/oliveira-icon.png',
    fullLogoUrl: '/images/oliveira-logo.png',
    whatsappNumber: '5581988880002',
    whatsappFormatted: '+55 81 98888-0002',
    email: 'contato@mareresort.com.br',
    businessHours: 'Segunda a Sábado — 09:00 às 18:00',
    primaryColor: '#C15C3D',
    primaryContrast: '#FFFFFF',
    secondaryColor: '#D4A373',
    backgroundColor: '#1A1210',
    sectionBg: '#1A1210',
    headerBg: 'rgba(26, 18, 16, 0.98)',
    headerBorder: 'rgba(193, 92, 61, 0.25)',
    perks: [
      { title: '100% LINHO PURO EUROPEU', desc: 'Fibras naturais pré-lavadas com toque macio e respirável' },
      { title: 'ACABAMENTO ARTESANAL', desc: 'Botões em madeira nobre e cortes fluidos atemporais' }
    ],
    categories: [
      {
        id: 'cat-mar-1',
        name: 'Camisas de Linho & Gola Cubana',
        slug: 'camisas-linho',
        description: 'Camisas gola padre e gola cubana em puro linho pré-lavado.',
        image: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=600&q=80'
      },
      {
        id: 'cat-mar-2',
        name: 'Bermudas & Shorts Riviera',
        slug: 'shorts-resort',
        description: 'Shorts de alfaiataria em linho e shorts náuticos de secagem ultrarrápida.',
        image: 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&q=80'
      },
      {
        id: 'cat-mar-3',
        name: 'Calças Fluidas de Linho Nobre',
        slug: 'calcas-linho',
        description: 'Calças em puro linho com cós elástico, cordão natural e corte relaxado.',
        image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80'
      },
      {
        id: 'cat-mar-4',
        name: 'Polos & Camisas Tricot Verão',
        slug: 'polos-tricot',
        description: 'Camisas polos em tricot tramado vazado e tecidos arejados de verão.',
        image: 'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=600&q=80'
      }
    ],
    products: [
      {
        id: 'mar-1',
        sku: 'MAR-CAM-001',
        name: 'Camisa Gola Cubana em Linho Puro Terracota',
        slug: 'camisa-gola-cubana-linho-puro-terracota',
        description: 'Camisa manga curta em 100% linho puro pré-encolhido com gola cubana retrô e botões ecológicos de coco. Caimento fluído e toque super fresco.',
        price: 219.90,
        promotionalPrice: 189.90,
        images: ['https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=1000&q=85', 'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=1000&q=85'],
        categoryId: 'cat-mar-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Terracota Solar', hex: '#c15c3d' }, { name: 'Areia Natural', hex: '#d4a373' }, { name: 'Branco Linho', hex: '#fdfbf7' }],
        composition: '100% Linho Europeu Puro Certificado',
        fit: 'Resort Relaxed Fit',
        washCare: 'Lavagem suave à mão ou máquina até 30°C. Secar à sombra.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'mar-2',
        sku: 'MAR-BER-002',
        name: 'Short Alfaiataria Resort Cordão Natural',
        slug: 'short-alfaiataria-resort-cordao-natural',
        description: 'Short leve com cós elástico anatômico e cordão em algodão cru trançado. Dois bolsos frontais alfaiataria e bolso traseiro com lapela.',
        price: 169.90,
        images: ['https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=1000&q=85'],
        categoryId: 'cat-mar-2',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Areia Natural', hex: '#d4a373' }, { name: 'Azul Mediterrâneo', hex: '#264653' }],
        composition: '55% Linho, 45% Algodão Nobre',
        fit: 'Conforto Moderno Acima do Joelho',
        washCare: 'Lavagem suave. Passar a ferro brando.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'mar-3',
        sku: 'MAR-CAM-003',
        name: 'Camisa Gola Padre Manga Longa Linho Cru',
        slug: 'camisa-gola-padre-manga-longa-linho-cru',
        description: 'Camisa refinada em puro linho com colarinho mandarim / gola padre, botões madreperolados e martingal nas mangas para ajuste dobrado despojado.',
        price: 249.90,
        promotionalPrice: 219.90,
        images: ['https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=1000&q=85'],
        categoryId: 'cat-mar-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Linho Cru Natural', hex: '#e6ded5' }, { name: 'Azul Céu', hex: '#93c5fd' }, { name: 'Branco Neve', hex: '#ffffff' }],
        composition: '100% Linho Francês Puro',
        fit: 'Modern Slim Resort Fit',
        washCare: 'Lavar em água fria. Não centrifugar em alta rotação.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'mar-4',
        sku: 'MAR-CAL-004',
        name: 'Calça Pantalona Fluida em Puro Linho Areia',
        slug: 'calca-pantalona-fluida-em-puro-linho-areia',
        description: 'Calça de corte reto amplo com cós elástico traseiro e cordão frontal. Tecido levemente tramado de linho com caimento arejado e fresco para dias ensolarados.',
        price: 279.90,
        images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=1000&q=85'],
        categoryId: 'cat-mar-3',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'Areia Duna', hex: '#d4a373' }, { name: 'Branco Alabastro', hex: '#fafaf9' }, { name: 'Terracota Suave', hex: '#b45309' }],
        composition: '100% Linho Puro Amaciado',
        fit: 'Relaxed Wide Leg',
        washCare: 'Lavagem delicada à mão ou em saquinho.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'mar-5',
        sku: 'MAR-SWM-005',
        name: 'Short de Banho Riviera Quick-Dry Peletizado',
        slug: 'short-de-banho-riviera-quick-dry-peletizado',
        description: 'Short náutico de banho em tecido tecnológico peletizado repelente a água. Secagem em menos de 10 minutos com sunga interna elástica ultra-confortável.',
        price: 159.90,
        promotionalPrice: 139.90,
        images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&q=85'],
        categoryId: 'cat-mar-2',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Listrado Riviera Navy', hex: '#1e3a8a' }, { name: 'Terracota Sunset', hex: '#c15c3d' }, { name: 'Verde Esmeralda', hex: '#047857' }],
        composition: '100% Poliéster Peletizado Water-Repellent',
        fit: 'Short Riviera Acima do Joelho',
        washCare: 'Enxaguar em água doce após piscina ou mar.',
        available: true,
        featured: false,
        isNew: true
      },
      {
        id: 'mar-6',
        sku: 'MAR-POL-006',
        name: 'Camisa Polo em Tricot Vazado Summer Breeze',
        slug: 'camisa-polo-em-tricot-vazado-summer-breeze',
        description: 'Polo confeccionada em tricot fino de algodão nobre com trama aberta respirável. Gola sem botões estilo polo capri e caimento relaxado para sunset parties.',
        price: 229.90,
        images: ['https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=1000&q=85'],
        categoryId: 'cat-mar-4',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Off-White Baunilha', hex: '#fef3c7' }, { name: 'Caramelo Dourado', hex: '#d97706' }],
        composition: '100% Algodão Mercerizado Penteado',
        fit: 'Relaxed Retro Polo',
        washCare: 'Secar na horizontal. Não pendurar para não deformar o tricot.',
        available: true,
        featured: false,
        isNew: true
      },
      {
        id: 'mar-7',
        sku: 'MAR-KIM-007',
        name: 'Kimono Resort Sunset em Linho & Viscose',
        slug: 'kimono-resort-sunset-em-linho-e-viscose',
        description: 'Kimono unissex com manga 3/4 fluida, acabamento pespontado limpo e faixa opcional para amarração. Ideal para o fim de tarde na praia, marina ou resort.',
        price: 239.90,
        images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=1000&q=85', 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1000&q=85'],
        categoryId: 'cat-mar-1',
        sizes: ['P/M', 'G/GG'],
        colors: [{ name: 'Terracota Âmbar', hex: '#c15c3d' }, { name: 'Areia Rústico', hex: '#d4a373' }],
        composition: '55% Linho Nobre, 45% Viscose Fluida',
        fit: 'Oversized Flow Fit',
        washCare: 'Lavar à mão com água fria.',
        available: true,
        featured: true,
        isNew: false
      }
    ]
  },

  // =========================================================================
  // 5. TERRA FORTE — MODA COUNTRY & VAQUEJADA (ESTILO SERTANEJO)
  // =========================================================================
  terra_forte: {
    id: 'terra_forte',
    name: 'Terra Forte',
    segment: 'Moda Country & Vaquejada',
    badge: 'ESTILO SERTANEJO',
    tagline: 'MODA COUNTRY & COURO NOBRE',
    description: 'Camisas estruturadas em algodão encorpado, jaquetas em couro legítimo e chapéus moldados para quem vive o campo, a vaquejada e os grandes rodeios.',
    aboutEyebrow: 'TRADIÇÃO & CAMPO',
    aboutTitle: 'A autenticidade da vaquejada com elegância.',
    aboutText: 'A Terra Forte veste quem tem paixão pela terra, cavalos e tradição sertaneja. Roupas com costura reforçada e matéria-prima selecionada para aguentar a lida e brilhar na festa.',
    heroImage: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1200&q=85',
    logoUrl: '/vaquejada.png',
    fullLogoUrl: '/vaquejada.png',
    whatsappNumber: '5587977770003',
    whatsappFormatted: '+55 87 97777-0003',
    email: 'vendas@terrafortecountry.com.br',
    businessHours: 'Segunda a Sábado — 08:00 às 18:00',
    primaryColor: '#D97706',
    primaryContrast: '#FFFFFF',
    secondaryColor: '#B45309',
    backgroundColor: '#140E0A',
    sectionBg: '#140E0A',
    headerBg: 'rgba(20, 14, 10, 0.98)',
    headerBorder: 'rgba(217, 119, 6, 0.25)',
    perks: [
      { title: 'COURO BOVINO 100% LEGÍTIMO', desc: 'Trabalho artesanal com acabamento reforçado de alta durabilidade' },
      { title: 'RESISTÊNCIA & TRADIÇÃO', desc: 'Modelagens autênticas desenhadas para o campo e eventos' }
    ],
    categories: [
      {
        id: 'cat-tf-1',
        name: 'Camisas Western & Flanelas Xadrez',
        slug: 'camisas-country',
        description: 'Camisas western estruturadas com botões de pressão e pala bordada.',
        image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80'
      },
      {
        id: 'cat-tf-2',
        name: 'Calças Jeans Bootcut & Texana',
        slug: 'calcas-texanas',
        description: 'Calças jeans resistentes com corte bootcut ideal para uso com botas.',
        image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80'
      },
      {
        id: 'cat-tf-3',
        name: 'Couro Nobre, Coletes & Jaquetas',
        slug: 'jaquetas-couro',
        description: 'Jaquetas em couro legítimo amaciado e coletes resistentes de lona.',
        image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=600&q=80'
      },
      {
        id: 'cat-tf-4',
        name: 'Cintos & Acessórios de Vaquejada',
        slug: 'cintos-acessorios',
        description: 'Cintos de couro entalhado, bonés trucker e acessórios sertanejos.',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80'
      }
    ],
    products: [
      {
        id: 'tf-1',
        sku: 'TF-CAM-001',
        name: 'Camisa Western Tradicional Sarja Âmbar',
        slug: 'camisa-western-tradicional-sarja-ambar',
        description: 'Camisa western em sarja de algodão encorpada com costura tripla reforçada, botões de pressão perolados e pala clássica de vaquejada.',
        price: 199.90,
        promotionalPrice: 179.90,
        images: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1000&q=85'],
        categoryId: 'cat-tf-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Âmbar Dourado', hex: '#d97706' }, { name: 'Azul Petróleo Western', hex: '#1e3a5f' }, { name: 'Branco Fazenda', hex: '#fafafa' }],
        composition: '100% Algodão Encorpado 210g',
        fit: 'Western Comfort Fit',
        washCare: 'Lavagem à máquina até 40°C. Não alvejar.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'tf-2',
        sku: 'TF-JAC-002',
        name: 'Jaqueta Bomber Couro Bovino Rústico',
        slug: 'jaqueta-bomber-couro-bovino-rustico',
        description: 'Jaqueta produzida artesanalmente em couro legítimo atanado com forro interno térmico acetinado e metais antioxidantes ouro velho.',
        price: 890.00,
        promotionalPrice: 799.00,
        images: ['https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=1000&q=85'],
        categoryId: 'cat-tf-3',
        sizes: ['M', 'G', 'GG'],
        colors: [{ name: 'Marrom Tabaco', hex: '#451a03' }, { name: 'Preto Rústico', hex: '#1c1917' }],
        composition: '100% Couro Bovino Legítimo, Forro 100% Poliéster Acetinado',
        fit: 'Regular Western Fit',
        washCare: 'Limpeza especializada em couro. Hidratar periodicamente.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'tf-3',
        sku: 'TF-XAD-003',
        name: 'Camisa Xadrez Western Pérola Snap Flanelada',
        slug: 'camisa-xadrez-western-perola-snap-flanelada',
        description: 'Camisa western xadrez encorpada com pala bordada, bolsos chanfrados e botões de pressão madreperolados. Tecido flanelado macio e ultra durável.',
        price: 219.90,
        promotionalPrice: 189.90,
        images: ['https://images.unsplash.com/photo-1484517186945-df8151a1a871?w=1000&q=85'],
        categoryId: 'cat-tf-1',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Vermelho & Preto Buffalo', hex: '#991b1b' }, { name: 'Azul Royal & Navy', hex: '#1d4ed8' }, { name: 'Verde Mata & Caramelo', hex: '#166534' }],
        composition: '100% Algodão Flanelado 220g',
        fit: 'Western Regular',
        washCare: 'Lavagem em água fria. Secar à sombra.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'tf-4',
        sku: 'TF-JNS-004',
        name: 'Calça Jeans Texana Bootcut com Elastano 14oz',
        slug: 'calca-jeans-texana-bootcut-com-elastano-14oz',
        description: 'Modelagem texana bootcut autêntica com barra desenhada para cobrir o cano da bota com perfeição. Jeans 14oz com 2% de elastano para conforto na sela e no dia a dia.',
        price: 259.90,
        images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=1000&q=85'],
        categoryId: 'cat-tf-2',
        sizes: ['38', '40', '42', '44', '46'],
        colors: [{ name: 'Stone Washed Médio', hex: '#334155' }, { name: 'Índigo Escuro Tradicional', hex: '#1e293b' }],
        composition: '98% Algodão Denim Pesado 14oz, 2% Elastano',
        fit: 'Bootcut Texano',
        washCare: 'Lavar à máquina do avesso em água fria.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'tf-5',
        sku: 'TF-COL-005',
        name: 'Colete de Lona Encerada & Forro Xadrez Rústico',
        slug: 'colete-de-lona-encerada-e-forro-xadrez-rustico',
        description: 'Colete térmico resistente ao vento e poeira em lona de algodão pesada com forro interno acolchoado flanelado xadrez. Zíper de metal ouro velho com puxador de couro.',
        price: 329.90,
        promotionalPrice: 289.90,
        images: ['https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=1000&q=85'],
        categoryId: 'cat-tf-3',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Marrom Canela', hex: '#78350f' }, { name: 'Preto Carvão', hex: '#18181b' }],
        composition: 'Lona 100% Algodão Heavy Duty, Forro 100% Flanela Térmica',
        fit: 'Regular Utility Fit',
        washCare: 'Limpar a seco ou com esponja úmida.',
        available: true,
        featured: false,
        isNew: true
      },
      {
        id: 'tf-6',
        sku: 'TF-CIN-006',
        name: 'Cinto Couro Bovino Entalhado Fivela Western',
        slug: 'cinto-couro-bovino-entalhado-fivela-western',
        description: 'Couro legítimo bovino selecionado com entalhes florais em alto relevo feitos manualmente. Fivela removível em zamac prateado envelhecido com detalhes texanos.',
        price: 169.90,
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000&q=85'],
        categoryId: 'cat-tf-4',
        sizes: ['90cm', '95cm', '100cm', '105cm', '110cm'],
        colors: [{ name: 'Marrom Havana', hex: '#451a03' }, { name: 'Preto Western', hex: '#09090b' }],
        composition: '100% Couro Bovino Genuíno Selecionado',
        fit: 'Largura 4.0cm Western Padrão',
        washCare: 'Hidratar com cera para couro a cada 6 meses.',
        available: true,
        featured: false,
        isNew: false
      },
      {
        id: 'tf-7',
        sku: 'TF-BNE-007',
        name: 'Boné Trucker Country Terra Forte Bordado Relevo',
        slug: 'bone-trucker-country-terra-forte-bordado-relevo',
        description: 'Boné trucker com frente estruturada em sarja pesada, tela traseira respirável para ventilação e patch frontal bordado com fios reforçados. Fecho snapback ajustável.',
        price: 99.90,
        images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=1000&q=85', 'https://images.unsplash.com/photo-1516914943479-89db7d9ae7f2?w=1000&q=85'],
        categoryId: 'cat-tf-4',
        sizes: ['Único Ajustável'],
        colors: [{ name: 'Café & Marrom', hex: '#78350f' }, { name: 'Preto & Grafite', hex: '#18181b' }],
        composition: 'Frente: 100% Algodão Sarja, Tela: 100% Poliéster',
        fit: 'Trucker Snapback',
        washCare: 'Limpar à mão com pano úmido.',
        available: true,
        featured: false,
        isNew: true
      }
    ]
  },

  // =========================================================================
  // 6. ATELIER AURA — ALFAIATARIA & LUXO MINIMALISTA (CONTEMPORARY LUXURY)
  // =========================================================================
  atelier_aura: {
    id: 'atelier_aura',
    name: 'Atelier Aura',
    segment: 'Alfaiataria & Luxo Minimalista',
    badge: 'ALTA COSTURA',
    tagline: 'CONTEMPORARY LUXURY',
    description: 'Alfaiataria estruturada de precisão, proporções amplas e tecidos nobres italianos. O ápice da sofisticação silenciosa para o guarda-roupa contemporâneo.',
    aboutEyebrow: 'CONTEMPORARY TAILORING',
    aboutTitle: 'Design silencioso. Matéria-prima impecável.',
    aboutText: 'O Atelier Aura explora o corte perfeito, linhas limpas e tecidos excepcionais. Peças de presença sutil criadas para ultrapassar temporadas com máxima elegância.',
    heroImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&q=85',
    logoUrl: '/images/oliveira-icon.png',
    fullLogoUrl: '/images/oliveira-logo.png',
    whatsappNumber: '5511955550004',
    whatsappFormatted: '+55 11 95555-0004',
    email: 'concierge@atelier-aura.com',
    businessHours: 'Segunda a Sábado — 10:00 às 20:00 (Com agendamento)',
    primaryColor: '#F5F5F7',
    primaryContrast: '#0E0E10',
    secondaryColor: '#D1D5DB',
    backgroundColor: '#0E0E10',
    sectionBg: '#0E0E10',
    headerBg: 'rgba(14, 14, 16, 0.98)',
    headerBorder: 'rgba(255, 255, 255, 0.15)',
    perks: [
      { title: 'ALFAIATARIA DE PRECISÃO', desc: 'Cortes limpos, ombreiras estruturadas e caimento fluido' },
      { title: 'TECIDOS NOBRES IMPORTADOS', desc: 'Lã fria, seda pura e acabamentos manuais de alfaiate' }
    ],
    categories: [
      {
        id: 'cat-aur-1',
        name: 'Blazers & Paletós de Alfaiataria',
        slug: 'blazers-alfaiataria',
        description: 'Blazers estruturados e paletós sob medida contemporâneos.',
        image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80'
      },
      {
        id: 'cat-aur-2',
        name: 'Calças com Pregas Italianas',
        slug: 'calcas-nobres',
        description: 'Pantalonas de cós alto com pregas duplas e caimento arquitetônico.',
        image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&q=80'
      },
      {
        id: 'cat-aur-3',
        name: 'Camisaria Nobre & Algodão Egípcio',
        slug: 'camisaria-nobre',
        description: 'Camisas sociais em algodão egípcio 120 fios e camisetas em Pima peruano.',
        image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&q=80'
      },
      {
        id: 'cat-aur-4',
        name: 'Suéteres de Cashmere & Lã Merino',
        slug: 'cashmere-merino',
        description: 'Tricots finos em lã merino extrafina e blusas de gola alta atemporais.',
        image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=80'
      }
    ],
    products: [
      {
        id: 'aur-1',
        sku: 'AUR-BLZ-001',
        name: 'Blazer Estruturado em Lã Fria Super 120s',
        slug: 'blazer-estruturado-la-fria-super-120s',
        description: 'Blazer de alfaiataria em lã fria italiana Super 120s com meio forro de seda, ombreiras sutis e lapela notched de proporções impecáveis.',
        price: 980.00,
        promotionalPrice: 890.00,
        images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=1000&q=85', 'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?w=1000&q=85'],
        categoryId: 'cat-aur-1',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'Preto Grafite', hex: '#0e0e10' }, { name: 'Off-White Giz', hex: '#f5f5f7' }, { name: 'Azul Marinho Noturno', hex: '#0f172a' }],
        composition: '98% Lã Fria Italiana Super 120s, 2% Elastano Nobre',
        fit: 'Tailored Precision Fit',
        washCare: 'Lavagem a seco especializada em alfaiataria.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'aur-2',
        sku: 'AUR-PAN-002',
        name: 'Pantalona Ampla Pregas Duplas Alfaiataria',
        slug: 'pantalona-ampla-pregas-duplas-alfaiataria',
        description: 'Pantalona fluída com pregas duplas frontais, bolsos faca e acabamento interno de alfaiataria tradicional. Caimento alongado e refinado.',
        price: 520.00,
        promotionalPrice: 470.00,
        images: ['https://images.unsplash.com/photo-1544441893-675973e31985?w=1000&q=85'],
        categoryId: 'cat-aur-2',
        sizes: ['36', '38', '40', '42'],
        colors: [{ name: 'Preto Ônix', hex: '#0e0e10' }, { name: 'Pérola Acetinado', hex: '#e5e7eb' }, { name: 'Bege Areia Nobre', hex: '#d6d3d1' }],
        composition: '70% Viscose Nobre, 30% Linho com toque de seda',
        fit: 'High-Waist Wide Leg',
        washCare: 'Lavagem suave ou limpeza a seco.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'aur-3',
        sku: 'AUR-CAM-003',
        name: 'Camisa Social Puro Algodão Egípcio 120 Fios',
        slug: 'camisa-social-puro-algodao-egipcio-120-fios',
        description: 'Confeccionada em algodão egípcio Giza 120 fios com toque sedoso ultra-refinado. Colarinho semi-italiano, entretela alemã fusionada e botões em madrepérola natural australiana.',
        price: 420.00,
        images: ['https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=1000&q=85'],
        categoryId: 'cat-aur-3',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Branco Alabastro', hex: '#ffffff' }, { name: 'Azul Glacial', hex: '#e0f2fe' }, { name: 'Preto Noite', hex: '#0f172a' }],
        composition: '100% Algodão Egípcio Giza Fio 120/2',
        fit: 'Modern Tailored Slim',
        washCare: 'Lavagem suave. Passar a ferro a vapor.',
        available: true,
        featured: true,
        isNew: false
      },
      {
        id: 'aur-4',
        sku: 'AUR-SUT-004',
        name: 'Suéter Gola Alta Rolê em Lã Merino Australiana',
        slug: 'sueter-gola-alta-role-em-la-merino-australiana',
        description: 'Tricot fino em 100% lã merino extrafina 19.5 micra que proporciona regulação térmica inteligente sem pinicar. Gola alta canelada elegante e punhos anatômicos.',
        price: 590.00,
        promotionalPrice: 520.00,
        images: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1000&q=85'],
        categoryId: 'cat-aur-4',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Preto Puro', hex: '#0e0e10' }, { name: 'Bege Fendi', hex: '#a8a29e' }, { name: 'Cinza Mescla Nobre', hex: '#475569' }],
        composition: '100% Lã Merino Australiana Extrafina',
        fit: 'Tailored Knit Fit',
        washCare: 'Lavar à mão em água fria com sabão para lãs. Secar horizontal.',
        available: true,
        featured: true,
        isNew: true
      },
      {
        id: 'aur-5',
        sku: 'AUR-CAL-005',
        name: 'Calça Alfaiataria Sartorial com Fivelas Laterais',
        slug: 'calca-alfaiataria-sartorial-com-fivelas-laterais',
        description: 'Calça sem passantes com ajuste por fivelas metálicas laterais (side adjusters), bolso moeda embutido e barra italiana feita à mão. Pura elegância alfaiate.',
        price: 490.00,
        images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1000&q=85'],
        categoryId: 'cat-aur-2',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'Cinza Chumbo', hex: '#334155' }, { name: 'Azul Marinho Royal', hex: '#0f172a' }],
        composition: '98% Lã Fria Tropical, 2% Elastano',
        fit: 'Slim Tapered Sartorial',
        washCare: 'Lavagem a seco.',
        available: true,
        featured: false,
        isNew: true
      },
      {
        id: 'aur-6',
        sku: 'AUR-TEE-006',
        name: 'Camiseta Pima Luxury Minimal Touch',
        slug: 'camiseta-pima-luxury-minimal-touch',
        description: 'Camiseta desenvolvida com algodão Pima peruano colhido manualmente. Toque acetinado de seda, costuras invisíveis e gola canelada fina contemporânea.',
        price: 240.00,
        images: ['https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=1000&q=85'],
        categoryId: 'cat-aur-3',
        sizes: ['P', 'M', 'G', 'GG'],
        colors: [{ name: 'Preto Ônix', hex: '#0e0e10' }, { name: 'Branco Off', hex: '#f8fafc' }, { name: 'Verde Oliva Fumo', hex: '#3f4238' }],
        composition: '100% Algodão Pima Peruano Extra Long Staple',
        fit: 'Clean Regular Fit',
        washCare: 'Lavar em água fria no ciclo delicado.',
        available: true,
        featured: false,
        isNew: false
      },
      {
        id: 'aur-7',
        sku: 'AUR-CAS-007',
        name: 'Sobretudo Chesterfield em Cashmere & Lã Batida',
        slug: 'sobretudo-chesterfield-em-cashmere-e-la-batida',
        description: 'Casaco sobretudo longo de alfaiataria em blend de lã batida italiana com 30% cashmere virgem. Lapela notched de proporções impecáveis e forro acetinado.',
        price: 1490.00,
        promotionalPrice: 1290.00,
        images: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1000&q=85', 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1000&q=85'],
        categoryId: 'cat-aur-1',
        sizes: ['38', '40', '42', '44'],
        colors: [{ name: 'Preto Absoluto', hex: '#0e0e10' }, { name: 'Camel Italiano', hex: '#b45309' }],
        composition: '70% Lã Batida Nobre, 30% Cashmere Virgem',
        fit: 'Tailored Overcoat Fit',
        washCare: 'Limpeza a seco especializada.',
        available: true,
        featured: true,
        isNew: true
      }
    ]
  }
};
